version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 0894226808zZ
      MYSQL_DATABASE: clintun_nx
      MYSQL_USER: clintun_nx
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: clintun_nx
      PMA_PASSWORD: 0894226808zZ
      UPLOAD_LIMIT: 300M
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:

# สร้างและเริ่ม containers
# docker-compose up -d

# # ดูสถานะ containers ที่กำลังทำงาน
# docker ps

# # ดู logs
# docker-compose logs

# # หยุดการทำงาน containers
# docker-compose down

# # รีสตาร์ท containers
# docker-compose restart

# # หยุด containers
# docker-compose stop

# # เริ่ม containers
# docker-compose start


# อัพ
# git push -u origin main